# **Ahmet Selçuk KÜREN Staj Çalışmaları**
# **Pandas Nedir ?**
Pandas kütüphanesi ile veri organize edilerek analizler daha kolay ve hızlı yapılır. Pandas Python’ın en önemli kütüphanelerinden biridir.
# 1. Pandas Özellikleri
## Pandas Series
## Veri Okuma (Reading Data)
## Veriye Hızlı Bakış (Quick Look at Data)
## Pandas'ta Seçim İşlemleri (Selection in Pandas)
## Toplulaştırma ve Gruplama (Aggregation & Grouping)
## Apply ve Lambda
## Birleştirme (Join) İşlemleri

**Pandas Series**

In [5]:
import pandas as pd

In [6]:
s = pd.Series([10, 77, 12, 4, 5]) #pandas veri seti oluşturma
s

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [7]:
type(s) # veri setinin tipini bize söyler.

pandas.core.series.Series

**Veri Okuma (Reading Data)**

In [9]:
df = pd.read_csv("Spotify Quarterly.csv")

In [10]:
df.head() # ilk 5 satırı getirir.

,Date,Total Revenue,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost
0,31-03-2023,3042.0,2276.0,776.0,2713.0,1937.0,776.0,329.0,339.0,-10.0,515.0,210.0,317.0,4.32,347.0,435.0,140.0
1,31-12-2022,3166.0,2365.0,801.0,2717.0,1939.0,778.0,449.0,426.0,23.0,489.0,205.0,295.0,4.55,453.0,415.0,164.0
2,30-09-2022,3036.0,2286.0,750.0,2651.0,1908.0,743.0,385.0,378.0,7.0,456.0,195.0,273.0,4.63,432.0,386.0,160.0
3,30-06-2022,2864.0,2160.0,704.0,2504.0,1804.0,700.0,360.0,356.0,4.0,433.0,188.0,265.0,4.54,391.0,336.0,171.0
4,31-03-2022,2661.0,1990.0,671.0,2379.0,1704.0,675.0,282.0,286.0,-4.0,422.0,182.0,252.0,4.38,296.0,250.0,131.0

In [11]:
df.tail() #son 5 satırı getirir.

,Date,Total Revenue,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost
21,31-12-2017,1449.0,867.0,582.0,1018.0,761.0,257.0,130.0,106.0,24.0,160.0,71.0,93.0,5.24,173.0,123.0,73.0
22,30-09-2017,1032.0,802.0,230.0,923.0,711.0,212.0,109.0,91.0,18.0,150.0,62.0,91.0,5.06,138.0,98.0,67.0
23,30-06-2017,1007.0,775.0,232.0,904.0,686.0,218.0,103.0,89.0,14.0,138.0,59.0,83.0,5.53,146.0,95.0,70.0
24,31-03-2017,902.0,797.0,105.0,828.0,710.0,118.0,74.0,87.0,-13.0,131.0,52.0,82.0,5.46,110.0,80.0,54.0
25,31-12-2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.00,NaN,NaN,NaN

In [12]:
df.shape # satır ve sütün sayısını getirir.

(26, 17)

In [13]:
df.info() # sütünlar hakkında bilgilendirme yapar.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Date                           26 non-null     object
 1   Total Revenue                  25 non-null     float64
 2   Cost of Revenue                25 non-null     float64
 3   Gross Profit                   25 non-null     float64
 4   Premium Revenue                25 non-null     float64
 5   Premium Cost Revenue           25 non-null     float64
 6   Premium Gross Profit           25 non-null     float64
 7   Ad Revenue                     25 non-null     float64
 8   Ad Cost of revenue             25 non-null     float64
 9   Ad gross Profit                25 non-null     float64
 10  MAUs                           25 non-null     float64
 11  Premium MAUs                   25 non-null     float64
 12  Ad MAUs                        25 non-null     float64
 13  Premium ARPU                   26 non-null     float64
 14  Sales and Marketing Cost       25 non-null     float64
 15  Research and Development Cost  25 non-null     float64
 16  Genreal and Adminstraive Cost  25 non-null     float64
dtypes: float64(16), object(1)
memory usage: 3.6+ KB

In [14]:
df.describe().T # sütunların eleman sayısını, ortalamasını, standart sapmasını vb. değerkeri getirir.

,count,mean,std,min,25%,50%,75%,max
Total Revenue,25.0,1949.200000,688.571468,902.00,1449.000,1855.00,2501.0000,3166.0
Cost of Revenue,25.0,1448.320000,511.590634,775.00,1010.000,1381.00,1833.0000,2365.0
Gross Profit,25.0,501.280000,188.493484,105.00,373.000,479.00,668.0000,801.0
Premium Revenue,25.0,1721.400000,599.337203,828.00,1210.000,1700.00,2178.0000,2717.0
Premium Cost Revenue,25.0,1247.040000,409.621419,686.00,894.000,1219.00,1545.0000,1939.0
Premium Gross Profit,25.0,474.360000,191.566977,118.00,316.000,481.00,633.0000,778.0
Ad Revenue,25.0,215.760000,107.578762,74.00,130.000,175.00,282.0000,449.0
Ad Cost of revenue,25.0,201.680000,105.019332,87.00,115.000,157.00,286.0000,426.0
Ad gross Profit,25.0,14.080000,15.739864,-16.00,4.000,18.00,25.0000,42.0
MAUs,25.0,294.720000,117.212599,131.00,191.000,286.00,381.0000,515.0
Premium MAUs,25.0,130.080000,49.435918,52.00,87.000,130.00,172.0000,210.0
Ad MAUs,25.0,172.520000,71.702580,82.00,109.000,163.00,220.0000,317.0
Premium ARPU,26.0,4.702308,0.452560,4.12,4.385,4.64,4.8825,6.0
Sales and Marketing Cost,25.0,243.840000,95.165505,110.00,172.000,236.00,294.0000,453.0
Research and Development Cost,25.0,203.000000,101.236522,80.00,135.000,173.00,253.0000,435.0
Genreal and Adminstraive Cost,25.0,102.360000,34.507101,42.00,73.000,102.00,126.0000,171.0

In [15]:
df.isnull().values.any() # boş değer kontrolü yapar.

True

In [16]:
df.isnull().sum() # boş değerlerin sayısını getirir.

Date                             0
Total Revenue                    1
Cost of Revenue                  1
Gross Profit                     1
Premium Revenue                  1
Premium Cost Revenue             1
Premium Gross Profit             1
Ad Revenue                       1
Ad Cost of revenue               1
Ad gross Profit                  1
MAUs                             1
Premium MAUs                     1
Ad MAUs                          1
Premium ARPU                     0
Sales and Marketing Cost         1
Research and Development Cost    1
Genreal and Adminstraive Cost    1
dtype: int64

**Pandas'ta Seçim İşlemleri (Selection in Pandas)**

In [17]:
df.index

RangeIndex(start=0, stop=26, step=1)

In [18]:
df[0:13] # ilk 13 satırı getirir.

,Date,Total Revenue,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost
0,31-03-2023,3042.0,2276.0,776.0,2713.0,1937.0,776.0,329.0,339.0,-10.0,515.0,210.0,317.0,4.32,347.0,435.0,140.0
1,31-12-2022,3166.0,2365.0,801.0,2717.0,1939.0,778.0,449.0,426.0,23.0,489.0,205.0,295.0,4.55,453.0,415.0,164.0
2,30-09-2022,3036.0,2286.0,750.0,2651.0,1908.0,743.0,385.0,378.0,7.0,456.0,195.0,273.0,4.63,432.0,386.0,160.0
3,30-06-2022,2864.0,2160.0,704.0,2504.0,1804.0,700.0,360.0,356.0,4.0,433.0,188.0,265.0,4.54,391.0,336.0,171.0
4,31-03-2022,2661.0,1990.0,671.0,2379.0,1704.0,675.0,282.0,286.0,-4.0,422.0,182.0,252.0,4.38,296.0,250.0,131.0
5,31-12-2021,2689.0,1977.0,712.0,2295.0,1625.0,670.0,394.0,352.0,42.0,406.0,180.0,236.0,4.40,340.0,253.0,126.0
6,30-09-2021,2501.0,1833.0,668.0,2178.0,1545.0,633.0,323.0,288.0,35.0,381.0,172.0,220.0,4.34,280.0,208.0,105.0
7,30-06-2021,2331.0,1668.0,663.0,2056.0,1423.0,633.0,275.0,245.0,30.0,365.0,165.0,210.0,4.29,279.0,255.0,117.0
8,31-03-2021,2147.0,1599.0,548.0,1931.0,1393.0,538.0,216.0,206.0,10.0,356.0,158.0,208.0,4.12,236.0,196.0,102.0
9,31-12-2020,2168.0,1593.0,575.0,1887.0,1342.0,545.0,281.0,251.0,30.0,345.0,155.0,199.0,4.26,294.0,232.0,118.0
10,30-09-2020,1975.0,1486.0,489.0,1790.0,1302.0,488.0,185.0,184.0,1.0,320.0,144.0,185.0,4.19,256.0,176.0,97.0
11,30-06-2020,1889.0,1410.0,479.0,1758.0,1263.0,495.0,131.0,147.0,-16.0,299.0,138.0,170.0,4.41,248.0,267.0,131.0
12,31-03-2020,1848.0,1376.0,472.0,1700.0,1219.0,481.0,148.0,157.0,-9.0,286.0,130.0,163.0,4.42,231.0,162.0,96.0

In [19]:
df.drop(0, axis=0).head() # 0. satırı kaldırır. [axis=0 satırı , axis=1 sütunu seçer.]

,Date,Total Revenue,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost
1,31-12-2022,3166.0,2365.0,801.0,2717.0,1939.0,778.0,449.0,426.0,23.0,489.0,205.0,295.0,4.55,453.0,415.0,164.0
2,30-09-2022,3036.0,2286.0,750.0,2651.0,1908.0,743.0,385.0,378.0,7.0,456.0,195.0,273.0,4.63,432.0,386.0,160.0
3,30-06-2022,2864.0,2160.0,704.0,2504.0,1804.0,700.0,360.0,356.0,4.0,433.0,188.0,265.0,4.54,391.0,336.0,171.0
4,31-03-2022,2661.0,1990.0,671.0,2379.0,1704.0,675.0,282.0,286.0,-4.0,422.0,182.0,252.0,4.38,296.0,250.0,131.0
5,31-12-2021,2689.0,1977.0,712.0,2295.0,1625.0,670.0,394.0,352.0,42.0,406.0,180.0,236.0,4.40,340.0,253.0,126.0

In [20]:
df["Total Revenue"].head()

0    3042.0
1    3166.0
2    3036.0
3    2864.0
4    2661.0
Name: Total Revenue, dtype: float64

In [21]:
df.drop("Total Revenue", axis=1, inplace=True)# Total Revenue sütununu kaldırmak için kullanılır.[inplace=True değişikliği kalıcı hale getirmek için kullanılır.]

In [22]:
df.head()

,Date,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost
0,31-03-2023,2276.0,776.0,2713.0,1937.0,776.0,329.0,339.0,-10.0,515.0,210.0,317.0,4.32,347.0,435.0,140.0
1,31-12-2022,2365.0,801.0,2717.0,1939.0,778.0,449.0,426.0,23.0,489.0,205.0,295.0,4.55,453.0,415.0,164.0
2,30-09-2022,2286.0,750.0,2651.0,1908.0,743.0,385.0,378.0,7.0,456.0,195.0,273.0,4.63,432.0,386.0,160.0
3,30-06-2022,2160.0,704.0,2504.0,1804.0,700.0,360.0,356.0,4.0,433.0,188.0,265.0,4.54,391.0,336.0,171.0
4,31-03-2022,1990.0,671.0,2379.0,1704.0,675.0,282.0,286.0,-4.0,422.0,182.0,252.0,4.38,296.0,250.0,131.0

**Değişkenler Üzerinde İşlemler**

In [23]:
col_names = ["Cost of Revenue", "Gross Profit", "Premium Revenue"]
df[col_names].head()

   Cost of Revenue  Gross Profit  Premium Revenue
0           2276.0         776.0           2713.0
1           2365.0         801.0           2717.0
2           2286.0         750.0           2651.0
3           2160.0         704.0           2504.0
4           1990.0         671.0           2379.0

In [24]:
df["Cost of Revenue2"] = df["Cost of Revenue"]**2
df["Cost of Revenue3"] = df["Cost of Revenue"] / df["Cost of Revenue2"]# yaptığımız matematiksel işlemler son sütunlara eklenir.
df.head()

,Date,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost,Cost of Revenue2,Cost of Revenue3
0,31-03-2023,2276.0,776.0,2713.0,1937.0,776.0,329.0,339.0,-10.0,515.0,210.0,317.0,4.32,347.0,435.0,140.0,5180176.0,0.000439
1,31-12-2022,2365.0,801.0,2717.0,1939.0,778.0,449.0,426.0,23.0,489.0,205.0,295.0,4.55,453.0,415.0,164.0,5593225.0,0.000423
2,30-09-2022,2286.0,750.0,2651.0,1908.0,743.0,385.0,378.0,7.0,456.0,195.0,273.0,4.63,432.0,386.0,160.0,5225796.0,0.000437
3,30-06-2022,2160.0,704.0,2504.0,1804.0,700.0,360.0,356.0,4.0,433.0,188.0,265.0,4.54,391.0,336.0,171.0,4665600.0,0.000463
4,31-03-2022,1990.0,671.0,2379.0,1704.0,675.0,282.0,286.0,-4.0,422.0,182.0,252.0,4.38,296.0,250.0,131.0,3960100.0,0.000503

**iloc & loc**


1.   iloc: tamsayı tabanlı seçim
2.   loc: etiket tabanlı seçim

In [25]:
df.iloc[0:3]# ilk 3 satırı getirir

,Date,Cost of Revenue,Gross Profit,Premium Revenue,Premium Cost Revenue,Premium Gross Profit,Ad Revenue,Ad Cost of revenue,Ad gross Profit,MAUs,Premium MAUs,Ad MAUs,Premium ARPU,Sales and Marketing Cost,Research and Development Cost,Genreal and Adminstraive Cost,Cost of Revenue2,Cost of Revenue3
0,31-03-2023,2276.0,776.0,2713.0,1937.0,776.0,329.0,339.0,-10.0,515.0,210.0,317.0,4.32,347.0,435.0,140.0,5180176.0,0.000439
1,31-12-2022,2365.0,801.0,2717.0,1939.0,778.0,449.0,426.0,23.0,489.0,205.0,295.0,4.55,453.0,415.0,164.0,5593225.0,0.000423
2,30-09-2022,2286.0,750.0,2651.0,1908.0,743.0,385.0,378.0,7.0,456.0,195.0,273.0,4.63,432.0,386.0,160.0,5225796.0,0.000437

In [26]:
df.iloc[0:3, 0:3]#ilk 3 satır ve ilk 3 sütunu getirir

         Date  Cost of Revenue  Gross Profit
0  31-03-2023           2276.0         776.0
1  31-12-2022           2365.0         801.0
2  30-09-2022           2286.0         750.0

In [27]:
df.loc[0:3, "Gross Profit"]#girilen sütuna göre satır getirir

0    776.0
1    801.0
2    750.0
3    704.0
Name: Gross Profit, dtype: float64

In [28]:
col_names = ["Cost of Revenue", "Gross Profit", "Premium Revenue"]
df.loc[0:3, col_names]

   Cost of Revenue  Gross Profit  Premium Revenue
0           2276.0         776.0           2713.0
1           2365.0         801.0           2717.0
2           2286.0         750.0           2651.0
3           2160.0         704.0           2504.0

**Toplulaştırma ve Gruplama (Aggregation & Grouping)**

In [29]:
df["Gross Profit"].mean()#ortalama almaya yarar

501.28

In [31]:
df.groupby("Gross Profit")["Premium Revenue"].mean()#gruplamak için groupby() kullanılır

Gross Profit
105.0     828.0
230.0     923.0
232.0     904.0
283.0    1037.0
329.0    1150.0
342.0    1210.0
373.0    1385.0
399.0    1320.0
434.0    1502.0
441.0    1561.0
472.0    1700.0
474.0    1638.0
479.0    1758.0
489.0    1790.0
548.0    1931.0
575.0    1887.0
582.0    1018.0
663.0    2056.0
668.0    2178.0
671.0    2379.0
704.0    2504.0
712.0    2295.0
750.0    2651.0
776.0    2713.0
801.0    2717.0
Name: Premium Revenue, dtype: float64

In [33]:
df.groupby("Gross Profit").agg({"Premium Revenue": ["mean", "sum"]})# sözlük yapısı ile ortalama , toplam ve min max  işlemleri yapılabilir

             Premium Revenue
                        mean     sum
Gross Profit
105.0                  828.0   828.0
230.0                  923.0   923.0
232.0                  904.0   904.0
283.0                 1037.0  1037.0
329.0                 1150.0  1150.0
342.0                 1210.0  1210.0
373.0                 1385.0  1385.0
399.0                 1320.0  1320.0
434.0                 1502.0  1502.0
441.0                 1561.0  1561.0
472.0                 1700.0  1700.0
474.0                 1638.0  1638.0
479.0                 1758.0  1758.0
489.0                 1790.0  1790.0
548.0                 1931.0  1931.0
575.0                 1887.0  1887.0
582.0                 1018.0  1018.0
663.0                 2056.0  2056.0
668.0                 2178.0  2178.0
671.0                 2379.0  2379.0
704.0                 2504.0  2504.0
712.0                 2295.0  2295.0
750.0                 2651.0  2651.0
776.0                 2713.0  2713.0
801.0                 2717.0  2717.0

**Pivot table**

PivotTable, verilerinize ilişkin karşılaştırmaları, kalıpları ve eğilimleri görmek amacıyla verileri hesaplamanıza, özetlemenize ve analiz etmenize yönelik güçlü bir araçtır.

In [39]:
df.pivot_table("Cost of Revenue", ["Premium Revenue", "Premium MAUs"])

                              Cost of Revenue
Premium Revenue Premium MAUs
828.0           52.0                    797.0
904.0           59.0                    775.0
923.0           62.0                    802.0
1018.0          71.0                    867.0
1037.0          75.0                    856.0
1150.0          83.0                    944.0
1210.0          87.0                   1010.0
1320.0          96.0                   1096.0
1385.0          100.0                  1138.0
1502.0          108.0                  1233.0
1561.0          113.0                  1290.0
1638.0          124.0                  1381.0
1700.0          130.0                  1376.0
1758.0          138.0                  1410.0
1790.0          144.0                  1486.0
1887.0          155.0                  1593.0
1931.0          158.0                  1599.0
2056.0          165.0                  1668.0
2178.0          172.0                  1833.0
2295.0          180.0                  1977.0
2379.0          182.0                  1990.0
2504.0          188.0                  2160.0
2651.0          195.0                  2286.0
2713.0          210.0                  2276.0
2717.0          205.0                  2365.0

**Apply ve Lambda**

apply() içerisinde kullan at fonksiyonu olan lambda kullanarak ek fonksiyon kullanmaya gerek kalmaz.

In [40]:
df.loc[:, df.columns.str.contains("Premium MAUs")].apply(lambda x: x/10).head()

   Premium MAUs
0          21.0
1          20.5
2          19.5
3          18.8
4          18.2

**Birleştirme (Join) İşlemleri**

1.   Merge ile Birleştirme İşlemleri
2.   Concat ile birleştirme işlemleri

In [41]:
df1 = pd.DataFrame({'employees': ['john', 'dennis', 'mark', 'maria'],
                    'group': ['accounting', 'engineering', 'engineering', 'hr']})

df2 = pd.DataFrame({'employees': ['mark', 'john', 'dennis', 'maria'],
                    'start_date': [2010, 2009, 2014, 2019]})

pd.merge(df1, df2)
pd.merge(df1, df2, on="employees")

  employees        group  start_date
0      john   accounting        2009
1    dennis  engineering        2014
2      mark  engineering        2010
3     maria           hr        2019

In [44]:
import numpy as np
m = np.random.randint(1, 30, size=(5, 3))
df1 = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df2 = df1 + 99

pd.concat([df1, df2], ignore_index=True)

   var1  var2  var3
0    16    29    18
1     4    27    14
2    11    27    11
3     3     9    15
4    17     6     9
5   115   128   117
6   103   126   113
7   110   126   110
8   102   108   114
9   116   105   108